examen2/api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    ### USUARIOS SERIALIZERS URLS
    path('u/list/usuarios/', views.ListUsuariosAPIView.as_view(), name="list_u_api"),
    path('u/create/usuarios/', views.CreateUsuariosAPIView.as_view(), name="create_u_api"),
    path('u/update/usuarios/<int:pk>/', views.UpdateUsuariosAPIView.as_view(), name="update_u_api"),

    ### ToDo SERIALIZERS URLS
    path('t/list/todo/', views.ListToDoAPIView.as_view(), name="list_u_api"),
    path('t/create/todo/', views.CreateToDoAPIView.as_view(), name="create_u_api"),
    path('t/update/todo/<int:pk>/', views.UpdateToDoAPIView.as_view(), name="update_u_api"),
]

examen2/core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    ##### USUARIOS URLS #####
    path('list/usuarios/', views.ListUsuario.as_view(), name="list_u"),
    path('new/usuarios/', views.NewUsuario.as_view(), name="create_u"),
    path('update/usuarios/<int:pk>/', views.UpdateUsuario.as_view(), name="update_u"),
    path('delete/usuarios/<int:pk>/', views.DeleteUsuario.as_view(), name="delete_u"),

    ##### ToDo URLS #####
    path('list/todo/', views.ListToDo.as_view(), name="list_t"),
    path('new/todo/', views.NewToDo.as_view(), name="create_t"),
    path('update/todo/<int:pk>/', views.UpdateToDo.as_view(), name="update_t"),
    path('delete/todo/<int:pk>/', views.DeleteToDo.as_view(), name="delete_t"),

    #### EXTRA URLS ####
    path('list/todo/pending/', views.ListToDoPending.as_view(), name="list_tp"),
    path('list/todo/pendingidt/', views.ListToDoPendingIDT.as_view(), name="list_tidt"),
    path('list/todo/pendingidtp/', views.ListToDoPendingIDTP.as_view(), name="list_tidtp"),
    path('list/todo/pendingidtpr/', views.ListToDoPendingIDTPR.as_view(), name="list_tidtpr"),

    path('list/usuarios/pending/', views.ListUsuariosPending.as_view(), name="list_up"),
    path('list/usuarios/pendingr/', views.ListUsuariosPendingR.as_view(), name="list_upr"),
    path('list/usuarios/pendingnr/', views.ListUsuariosPendingNR.as_view(), name="list_upnr"),
]

examen2/examen2/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

examen2/home/urls.py
from django.urls import path

from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),

    ### PROFILE URLS ###
    path('list/profile/', views.ListProfile.as_view(), name="list_profile"),
    path('detail/profile/<int:pk>/', views.DetailProfile.as_view(), name="detail_profile"),
]

examen2/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Agrega aquí tus estilos adicionales si es necesario -->
    <style>
        /* Estilos adicionales */
        .navbar {
            background-color: #343a40; /* Cambia el color de fondo de la barra de navegación */
        }
        .navbar-nav .nav-link {
            color: #ffffff !important; /* Cambia el color del texto de los enlaces del menú */
        }
        .nav-item.dropdown .dropdown-menu {
            background-color: #343a40; /* Cambia el color de fondo del menú desplegable */
        }
        .nav-item.dropdown .dropdown-menu .dropdown-item {
            color: #ffffff !important; /* Cambia el color del texto de los elementos del menú desplegable */
        }
        .nav-item.dropdown .dropdown-menu .dropdown-divider {
            border-top-color: #ffffff; /* Cambia el color del divisor del menú desplegable */
        }
        .navbar-toggler-icon {
            background-color: #ffffff; /* Cambia el color del icono del botón de navegación */
        }
        .navbar-toggler {
            border-color: #ffffff; /* Cambia el color del borde del botón de navegación */
        }
        .container-fluid {
            padding-left: 0;
            padding-right: 0;
        }
    </style>
</head>
<body>
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home:index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Users
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'core:list_u' %}">Users List</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:create_u' %}">New User</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:list_up' %}">Pending Users</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:list_upr' %}">Pending Resolved Users</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:list_upnr' %}">Pending Not Resolved Users</a></li>

                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            To Do
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'core:list_t' %}">ToDo List</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:create_t' %}">New ToDo</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:list_tp' %}">Pending ToDo</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:list_tidt' %}">Pending Titles</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:list_tidtp' %}">Not Resolved Titles</a></li>
                            <li><a class="dropdown-item" href="{% url 'core:list_tidtpr' %}">Pending Resolved Titles</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="navbar-nav me-right mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <span class="nav-link">{{ request.user }}</span>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<div class="container mt-4">
    {% block content %}
    {% endblock content %}
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>