examen2/api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    ### USUARIOS SERIALIZERS URLS
    path('u/list/usuarios/', views.ListUsuariosAPIView.as_view(), name="list_u_api"),
    path('u/create/usuarios/', views.CreateUsuariosAPIView.as_view(), name="create_u_api"),
    path('u/update/usuarios/<int:pk>/', views.UpdateUsuariosAPIView.as_view(), name="update_u_api"),

    ### ToDo SERIALIZERS URLS
    path('t/list/todo/', views.ListToDoAPIView.as_view(), name="list_u_api"),
    path('t/create/todo/', views.CreateToDoAPIView.as_view(), name="create_u_api"),
    path('t/update/todo/<int:pk>/', views.UpdateToDoAPIView.as_view(), name="update_u_api"),
]

examen2/core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    ##### USUARIOS URLS #####
    path('list/usuarios/', views.ListUsuario.as_view(), name="list_u"),
    path('new/usuarios/', views.NewUsuario.as_view(), name="create_u"),
    path('update/usuarios/<int:pk>/', views.UpdateUsuario.as_view(), name="update_u"),
    path('delete/usuarios/<int:pk>/', views.DeleteUsuario.as_view(), name="delete_u"),

    ##### ToDo URLS #####
    path('list/todo/', views.ListToDo.as_view(), name="list_t"),
    path('new/todo/', views.NewToDo.as_view(), name="create_t"),
    path('update/todo/<int:pk>/', views.UpdateToDo.as_view(), name="update_t"),
    path('delete/todo/<int:pk>/', views.DeleteToDo.as_view(), name="delete_t"),

    #### EXTRA URLS ####
    path('list/todo/pending/', views.ListToDoPending.as_view(), name="list_tp"),
    path('list/todo/pendingidt/', views.ListToDoPendingIDT.as_view(), name="list_tidt"),
    path('list/todo/pendingidtp/', views.ListToDoPendingIDTP.as_view(), name="list_tidtp"),
    path('list/todo/pendingidtpr/', views.ListToDoPendingIDTPR.as_view(), name="list_tidtpr"),

    path('list/usuarios/pending/', views.ListUsuariosPending.as_view(), name="list_up"),
    path('list/usuarios/pendingr/', views.ListUsuariosPendingR.as_view(), name="list_upr"),
    path('list/usuarios/pendingnr/', views.ListUsuariosPendingNR.as_view(), name="list_upnr"),
]

examen2/examen2/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

examen2/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.


class Usuarios(models.Model):
    username = models.CharField(max_length=50, default="Pedro", unique=True)

    def __str__(self):
        return self.username
    

class ToDo(models.Model):
    title = models.CharField(max_length=100, default="agregar titulo")
    user = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    pending = models.BooleanField(default=False)
    resolved = models.BooleanField(default=False)

    def __str__(self):
        return self.title

examen2/core/forms.py
from django import forms

from core import models

class NewUsuariosForm(forms.ModelForm):
    class Meta:
        model = models.Usuarios
        fields = [
            "username"
        ]
        widgets = {
            "username": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el  username"})
        }


class UpdateUsuariosForm(forms.ModelForm):
    class Meta:
        model = models.Usuarios
        fields = [
            "username"
        ]
        widgets = {
            "username": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el  username"})
        }


class NewToDoForm(forms.ModelForm):
    class Meta:
        model = models.ToDo
        fields = [
            "title",
            "user",
            "pending",
            "resolved"

        ]
        widgets = {
            "title": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal name!"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "pending": forms.CheckboxInput(attrs={"class":"form-check-input"}),
            "resolved": forms.CheckboxInput(attrs={"class":"form-check-input"})
        }


class UpdateToDoForm(forms.ModelForm):
    class Meta:
        model = models.ToDo
        fields = [
            "title",
            "user",
            "pending",
            "resolved"

        ]
        widgets = {
            "title": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el titulo"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "pending": forms.CheckboxInput(attrs={"class":"form-check-input"}),
            "resolved": forms.CheckboxInput(attrs={"class":"form-check-input"})
        }

examen2/core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

# Create your views here.

from core import models
from core import forms


### CRUD USUARIOS


# # # C R E A T E # # #
class NewUsuario(generic.CreateView):
    template_name = "core/create_u.html"
    model = models.Usuarios
    form_class = forms.NewUsuariosForm
    success_url = reverse_lazy("core:list_u")


# # L I S T
class ListUsuario(generic.ListView):
    template_name = "core/list_u.html"
    queryset = models.Usuarios.objects.all()


# # # U P D A T E # # #
class UpdateUsuario(generic.UpdateView):
    template_name = "core/update_u.html"
    model = models.Usuarios
    form_class = forms.UpdateUsuariosForm
    success_url = reverse_lazy("core:list_u")


# # # D E L E T E # # #
class DeleteUsuario(generic.DeleteView):
    template_name = "core/delete_u.html"
    model = models.Usuarios
    success_url = reverse_lazy("core:list_u")


### CRUD Todo


# # # C R E A T E # # #
class NewToDo(generic.CreateView):
    template_name = "core/create_t.html"
    model = models.ToDo
    form_class = forms.NewToDoForm
    success_url = reverse_lazy("core:list_t")

# # L I S T
class ListToDo(generic.ListView):
    template_name = "core/list_t.html"
    queryset = models.ToDo.objects.all()


# # # U P D A T E # # #
class UpdateToDo(generic.UpdateView):
    template_name = "core/update_t.html"
    model = models.ToDo
    form_class = forms.UpdateToDoForm
    success_url = reverse_lazy("core:list_t")
    context_object_name = 'todo'


# # # D E L E T E # # #
class DeleteToDo(generic.DeleteView):
    template_name = "core/delete_t.html"
    model = models.ToDo
    success_url = reverse_lazy("core:list_t")

### EXTRA LISTS

class ListToDoPending(generic.ListView):
    template_name = "core/list_tp.html"
    queryset = models.ToDo.objects.filter(pending=True)


class ListToDoPendingIDT(generic.ListView):
    template_name = "core/list_tidt.html"
    queryset = models.ToDo.objects.filter(pending=True)

class ListToDoPendingIDTP(generic.ListView):
    template_name = "core/list_tidtp.html"
    queryset = models.ToDo.objects.filter(pending=True, resolved=False)

class ListToDoPendingIDTPR(generic.ListView):
    template_name = "core/list_tidtpr.html"
    queryset = models.ToDo.objects.filter(pending=True, resolved=True)

class ListUsuariosPending(generic.ListView):
    template_name = "core/list_up.html"
    queryset = models.ToDo.objects.filter(pending=True)

class ListUsuariosPendingR(generic.ListView):
    template_name = "core/list_upr.html"
    queryset = models.ToDo.objects.filter(pending=True, resolved=True)

class ListUsuariosPendingNR(generic.ListView):
    template_name = "core/list_upnr.html"
    queryset = models.ToDo.objects.filter(pending=True, resolved=False)

examen2/templates/core/create_t.html
{% extends "base/base.html" %}

{% block title %}NEW TODO VIEW{% endblock title %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">New ToDo</h5>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-success">Create ToDo</button>
                            <a href="{% url 'core:list_t' %}" class="btn btn-warning">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

examen2/templates/core/delete_t.html
{% extends "base/base.html" %}

{% block title %}DELETE TODO VIEW{% endblock title %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Delete ToDo</h5>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <h2>¿Realmente deseas eliminar este ToDo? </h2>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-danger">Delete ToDo</button>
                            <a href="{% url 'core:list_t' %}" class="btn btn-warning">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

examen2/templates/core/delete_u.html
{% extends "base/base.html" %}

{% block title %}DELETE USUARIO VIEW{% endblock title %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Delete Usuario</h5>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <h2>¿Realmente deseas eliminar este usuario?</h2>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-danger">Delete Usuario</button>
                            <a href="{% url 'core:list_u' %}" class="btn btn-warning">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

examen2/templates/core/list_t.html
{% extends "base/base.html" %}

{% block title %}TODO LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_t' %}" class="btn btn-outline-success form-control">New ToDo</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>TITLE</th>
            <th>USER</th>
            <th>PENDING</th>
            <th>RESOLVED</th>
        </thead>
        <tbody>
            {% for t in object_list %}
                <tr>
                    <td>{{ t.id }}</td>
                    <td>{{ t.title }}</td>
                    <td>{{ t.user }}</td>
                    <td>{{ t.pending }}</td>
                    <td>{{ t.resolved }}</td>
                    <td><a href="{% url 'core:update_t' t.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_t' t.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

examen2/templates/core/list_tidt.html
{% extends "base/base.html" %}

{% block title %}TODO PENDING ID LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_t' %}" class="btn btn-outline-success form-control">New ToDo</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>TITLE</th>

        </thead>
        <tbody>
            {% for tidt in object_list %}
                <tr>
                    <td>{{ tidt.id }}</td>
                    <td>{{ tidt.title }}</td>

                    <td><a href="{% url 'core:update_t' tidt.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_t' tidt.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

examen2/templates/core/list_tidtp.html
{% extends "base/base.html" %}

{% block title %}TODO PENDING NOT RESOLVED LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_t' %}" class="btn btn-outline-success form-control">New ToDo</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>TITLE</th>

        </thead>
        <tbody>
            {% for tidtp in object_list %}
                <tr>
                    <td>{{ tidtp.id }}</td>
                    <td>{{ tidtp.title }}</td>

                    <td><a href="{% url 'core:update_t' tidtp.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_t' tidtp.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

examen2/templates/core/list_tidtpr.html
{% extends "base/base.html" %}

{% block title %}TODO PENDING RESOLVED LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_t' %}" class="btn btn-outline-success form-control">New ToDo</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>TITLE</th>

        </thead>
        <tbody>
            {% for tidtp in object_list %}
                <tr>
                    <td>{{ tidtpr.id }}</td>
                    <td>{{ tidtpr.title }}</td>

                    <td><a href="{% url 'core:update_t' tidtpr.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_t' tidtpr.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

examen2/templates/core/list_tp.html
{% extends "base/base.html" %}

{% block title %}TODO PENDING LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_t' %}" class="btn btn-outline-success form-control">New ToDo</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>

        </thead>
        <tbody>
            {% for tp in object_list %}
                <tr>
                    <td>{{ tp.id }}</td>

                    <td><a href="{% url 'core:update_t' tp.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_t' tp.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

examen2/templates/core/list_u.html
{% extends "base/base.html" %}

{% block title %}USUARIOS LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_u' %}" class="btn btn-outline-success form-control">New User</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>USERNAME</th>
        </thead>
        <tbody>
            {% for u in object_list %}
                <tr>
                    <td>{{ u.id }}</td>
                    <td>{{ u.username }} </td>
                    <td><a href="{% url 'core:update_u' u.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_u' u.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

examen2/templates/core/list_up.html
{% extends "base/base.html" %}

{% block title %}PENDING USERS LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_u' %}" class="btn btn-outline-success form-control">New User</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>USERNAME</th>
        </thead>
        <tbody>
            {% for up in object_list %}
                <tr>
                    <td>{{ up.id }}</td>
                    <td>{{ up.user }}</td>
                    <td><a href="{% url 'core:update_t' up.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_t' up.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

examen2/templates/core/list_upnr.html
{% extends "base/base.html" %}

{% block title %}PENDING NOT RESOLVED USERS LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_u' %}" class="btn btn-outline-success form-control">New User</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>USERNAME</th>
        </thead>
        <tbody>
            {% for upnr in object_list %}
                <tr>
                    <td>{{ upnr.id }}</td>
                    <td>{{ upnr.user }}</td>
                    <td><a href="{% url 'core:update_t' upnr.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_t' upnr.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

examen2/templates/core/list_upr.html
{% extends "base/base.html" %}

{% block title %}PENDING RESOLVED USERS LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_u' %}" class="btn btn-outline-success form-control">New User</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>USERNAME</th>
        </thead>
        <tbody>
            {% for upr in object_list %}
                <tr>
                    <td>{{ upr.id }}</td>
                    <td>{{ upr.user }}</td>
                    <td><a href="{% url 'core:update_t' upr.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_t' upr.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

examen2/templates/core/update_t.html
{% extends "base/base.html" %}

{% block title %}UPDATE TODO VIEW{% endblock title %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Update ToDo</h5>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Update ToDo</button>
                            <a href="{% url 'core:list_t' %}" class="btn btn-warning">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

examen2/templates/core/update_u.html
{% extends "base/base.html" %}

{% block title %}UPDATE USUARIO VIEW{% endblock title %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Update Usuario</h5>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Update Usuario</button>
                            <a href="{% url 'core:list_u' %}" class="btn btn-warning">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}